### ISSUE TITLE
Utility function for building wrapper/unwrapper lens?

### ISSUE THREAD

**Issue by fluffynukeit** [purescript-contrib/purescript-lens#15]
Does this library currently have a utility function for wrapping/unwrapping data types with a single data constructor, such as newtypes?   I think they are defined like this:

```
_MyNewType = lens (\(MyNewType a) -> a) (\_ n -> MyNewType a)
```
This seems like this specific pattern could be automated beyond just using the `lens` function to help out (although, thinking about it now, I'm not sure if the pattern match in the getter can be mechanized).

**Comment by fluffynukeit** [comment]
Maybe one possibility is some kind of `Unwrappable` typeclass (assuming one doesn't already exist), then a lens that invokes the typeclass wrap/unwrap functionality.  E.G. `myField1..unwrap..myField2..myField3..unwrap`

**Comment by paf31** [comment]
See also http://hackage.haskell.org/package/newtype

Actually this would make a neat Hackage library too.

**Comment by paf31** [comment]
I created a _very_ minimal port of that library [here](https://github.com/paf31/purescript-newtypes).

Adding lenses on top should be simple.

**Comment by joneshf** [comment]
There's something like that in the haskell version, https://hackage.haskell.org/package/lens-4.7/docs/Control-Lens-Wrapped.html But, nothing like that is in here. 

If you can come up with something that doesn't involve another typeclass or a data type (synonyms are fine) a PR here would be great. If it does require a new data type or typeclass (which is fine also), can you submit it to https://github.com/joneshf/purescript-optic? 

I want to keep this library as lightweight as possible with only synonyms if possible (I think there's still a typeclass somewhere) so that you can not depend on it if you choose not to, but people can still benefit from the ideas if you implement the synonyms.

**Comment by paf31** [comment]
Isn't `iso` the function you want then?

**Comment by joneshf** [comment]
Basically, yes.

**Comment by fluffynukeit** [comment]
A lot of good stuff in optic.  I had been looking at refractor as the place to find ready-made functionality built on top of lens, but optic looks much more developed.  `iso` does indeed look like what I'm searching for.

**Comment by joneshf** [comment]
They serve different purposes. `refractor` is just for predefined optics, and `optic` is for more advanced things than `Lens` and `Prism`.

I assume it's good to close this then?

**Comment by fluffynukeit** [comment]
Yes, I think so.
