### ISSUE TITLE
Add to Pursuit?

### ISSUE THREAD

**Issue by paf31** [purescript-contrib/purescript-lens#23]

**Comment by Thimoteus** [comment]
:+1:

**Comment by rintcius** [comment]
I have added a section in travis.yml (see https://github.com/purescript-contrib/purescript-lens/blob/master/.travis.yml#L15 ). With this it should publish to pursuit automatically when a tag is created. All you should need to do is add a `GITHUB_TOKEN` env. var to the settings of the repos here https://travis-ci.org/purescript-contrib/purescript-lens/settings

I guess `GITHUB_TOKEN` is not set for this repos yet? (because the tag that was just created did not trigger the package to be uploaded to pursuit) Maybe good to set it? Or if this is intentional for some reason I can remove the section in travis.

**Comment by joneshf** [comment]
I'll be glad to do it if you can explain what `GITHUB_TOKEN` is :smile:.

**Comment by rintcius** [comment]
```
If you don't already have one, get a GitHub API token by visiting https://github.com/settings/tokens/new. No scopes are required, since the token is only used for authentication.
```

That's a quote from https://pursuit.purescript.org/help which explains the process. It also mentions the use of `-no-push` which I think can be used to publish the version that's already tagged.

**Comment by garyb** [comment]
I've added one and re-ran the build, so it's published now: https://pursuit.purescript.org/packages/purescript-lens/2.0.0

I would just point out one thing though, @rintcius - https://github.com/purescript-contrib/purescript-profunctor-lenses is probably the more widely used lens library :wink: not that there's anything wrong with having `lens` too.

**Comment by rintcius** [comment]
@garyb great, thanks! 

I know about the profunctor lenses lib, just haven't looked into migrating to it yet. Will do later though.

**Comment by garyb** [comment]
Ah ok, that totally makes sense! I was just pointing it in case you were writing a new library with it.

I'll close this since it's resolved now 👍
